name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_ROLE_ARN: arn:aws:iam::747582436141:role/futosuto-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: futosuto-deploy-role-session
          aws-region: ap-northeast-1

      - name: Sync to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }}/futosuto --no-progress \
            --acl public-read --follow-symlinks --delete
